# Step 1: Set the base image to Node.js (choose a version that matches your local setup)
FROM node:18-alpine

# Step 2: Set the working directory inside the container
WORKDIR /servers

ARG REACT_APP_SERVER_URL
ENV REACT_APP_SERVER_URL=$REACT_APP_SERVER_URL

# Step 3: Copy the package.json and package-lock.json (if present) to install dependencies
COPY package*.json ./

# Step 4: Install dependencies
RUN npm install

# Step 5: Copy the rest of the project files to the container
COPY . .

# Step 6: Expose the port your app will be running on
EXPOSE 4000

# Step 7: Start the app when the container is run
CMD ["npm", "start"]
