FROM node:18-alpine

WORKDIR /react-cognito

COPY package*.json ./
RUN npm install

COPY . .

# Step 6: Build the React app for production
# Accept REACT_APP_SERVER_URL as a build argument
ARG REACT_APP_SERVER_URL
ENV REACT_APP_SERVER_URL=$REACT_APP_SERVER_URL

RUN npm run build

RUN npm install -g serve

EXPOSE 3000

# Inject runtime variables and serve the React app
CMD ["/bin/sh", "-c", "echo \"window.env = { REACT_APP_SERVER_URL: '$REACT_APP_SERVER_URL' };\" > /react-cognito/build/env.js && serve -s build -l 3000"]
